# As maiores empresas do mundo e seus países de origem:

## Dados Básicos:

In [103]:
import pandas as pd
import numpy as np
dados = pd.read_csv('arquivos/maiores_empresas_forbes.csv')

In [146]:
dados.head(2000)

,rank,global company,country,sales,profit,assets,market value
0,1,Berkshire Hathaway,United States,$276.09 B,$89.8 B,$958.78 B,$741.48 B
1,2,ICBC,China,$208.13 B,$54.03 B,"$5,518.51 B",$214.43 B
2,3,Saudi Arabian Oil Company (Saudi Aramco),Saudi Arabia,$400.38 B,$105.36 B,$576.04 B,"$2,292.08 B"
3,4,JPMorgan Chase,United States,$124.54 B,$42.12 B,"$3,954.69 B",$374.45 B
4,5,China Construction Bank,China,$202.07 B,$46.89 B,"$4,746.95 B",$181.32 B
...,...,...,...,...,...,...,...
1995,1995,"Shenzhen Feima International Supply Chain Co.,...",China,$37 M,$1.41 B,$166 M,$1.14 B
1996,1997,NMDC,India,$3.52 B,$1.41 B,$5.71 B,$6.4 B
1997,1997,Sichuan Changhong Electric,China,$15.72 B,$53.1 M,$12.11 B,$1.96 B
1998,1999,Credit Bank of Moscow,Russia,$2.53 B,$370.1 M,$45.15 B,$2.06 B
1999,1999,Satellite Chemical,China,$4.41 B,$931.3 M,$7.64 B,$9.52 B

In [105]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rank            2000 non-null   int64
 1   global company  2000 non-null   object
 2   country         2000 non-null   object
 3   sales           2000 non-null   object
 4   profit          2000 non-null   object
 5   assets          2000 non-null   object
 6   market value    2000 non-null   object
dtypes: int64(1), object(6)
memory usage: 109.5+ KB

In [106]:
dados.columns

Index(['rank ', 'global company', 'country', 'sales ', 'profit ', 'assets',
       'market value'],
      dtype='object')

In [107]:
dados.columns = dados.columns.str.strip()

In [108]:
list(dados['global company'].drop_duplicates())

['Berkshire Hathaway',
 'ICBC',
 'Saudi Arabian Oil Company (Saudi Aramco)',
 'JPMorgan Chase',
 'China Construction Bank',
 'Amazon',
 'Apple',
 'Agricultural Bank of China',
 'Bank of America',
 'Toyota Motor',
 'Alphabet',
 'Microsoft',
 'Bank of China',
 'Samsung Group',
 'ExxonMobil',
 'Shell',
 'Ping An Insurance Group',
 'Wells Fargo',
 'Verizon Communications',
 'AT&T',
 'PetroChina',
 'UnitedHealth Group',
 'Walmart',
 'China Merchants Bank',
 'Volkswagen Group',
 'Chevron',
 'Citigroup',
 'Tencent Holdings',
 'Total',
 'Postal Savings Bank Of China (PSBC)',
 'China Mobile',
 'Comcast',
 'Alibaba Group',
 'Meta Platforms',
 'Allianz',
 'Morgan Stanley',
 'Goldman Sachs Group',
 'HSBC Holdings',
 'Johnson & Johnson',
 'BNP Paribas',
 'Mercedes-Benz Group',
 'CVS Health',
 'Pfizer',
 'Softbank',
 'Sinopec',
 'Nestlé',
 'RBC',
 'AXA Group',
 'Gazprom',
 'BP',
 'Intel',
 'Nippon Telegraph & Tel',
 'Reliance Industries',
 'TD Bank Group',
 'Industrial Bank',
 'Sony',
 'Taiwan Semiconductor',
 'Santander',
 'Mitsubishi UFJ Financial',
 'Ford Motor',
 'LVMH Moët Hennessy Louis Vuitton',
 'Bank of Communications',
 'Procter & Gamble',
 'BMW Group',
 'Petrobras',
 'Deutsche Telekom',
 'AbbVie',
 'Novartis',
 'General Motors',
 'Equinor',
 'China Life Insurance',
 'Roche Holding',
 'AIA Group',
 'MetLife',
 'BHP Group',
 'The Home Depot',
 'Siemens',
 'American Express',
 'Stellantis',
 'Zurich Insurance Group',
 'Rosneft',
 'Rio Tinto',
 'Brookfield Asset Management',
 'Cigna',
 'Prudential Financial',
 'PepsiCo',
 'Merck & Co.',
 'Anthem',
 'Bank of Nova Scotia',
 'American International Group',
 'Glencore International',
 'Cisco Systems',
 'Anheuser-Busch InBev',
 'Walt Disney',
 'Chubb',
 'CITIC',
 'Lloyds Banking Group',
 'IBM',
 'Sanofi',
 'United Parcel Service',
 'British American Tobacco',
 'Honda Motor',
 'UBS',
 'Mitsubishi',
 'State Bank of India',
 'Commonwealth Bank',
 'Shanghai Pudong Development',
 'Raytheon Technologies',
 'Enel',
 'Eni',
 'Capital One',
 'Bristol Myers Squibb',
 'Coca-Cola',
 'Oracle',
 'Sberbank',
 'Bank of Montreal',
 'Vale',
 'EDF',
 'Thermo Fisher Scientific',
 'Credit Agricole',
 'AIRBUS',
 'Costco Wholesale',
 'Hon Hai Precision',
 'Unilever',
 'Charter Communications',
 'Sumitomo Mitsui Financial',
 'ConocoPhillips',
 'GlaxoSmithKline',
 'Intesa Sanpaolo',
 'Manulife',
 'US Bancorp',
 'BASF',
 'CNOOC',
 'Abbott Laboratories',
 'Iberdrola',
 'China Shenhua Energy',
 'Itaú Unibanco Holding',
 'Caterpillar',
 'Mitsui',
 'Itochu',
 'Charles Schwab',
 'Truist Financial',
 'Enbridge',
 'Hitachi',
 'KDDI',
 'Hyundai Motor',
 'Visa',
 'China Citic Bank',
 'Target',
 'Tesla',
 'BBVA-Banco Bilbao Vizcaya',
 'Deere & Company',
 'HDFC Bank',
 'Barclays',
 'Munich Re',
 'Japan Post Holdings',
 'Walgreens',
 'Danaher',
 'Generali Group',
 'Møller-Maersk',
 "Lowe's",
 'FedEx',
 'Deutsche Post',
 'Broadcom',
 'PNC Financial Services',
 'LukOil',
 'Medtronic',
 'SAP',
 'SK Hynix',
 'ENGIE',
 'Lockheed Martin',
 'BlackRock',
 'Westpac Banking Group',
 'Duke Energy',
 'Dell Technologies',
 'VINCI',
 'Tokio Marine Holdings',
 'América Móvil',
 'E.ON',
 'Anglo American',
 'Banco Bradesco',
 'Accenture',
 'ING Group',
 'Honeywell International',
 'Mizuho Financial',
 'Linde',
 'ArcelorMittal',
 'Canadian Imperial Bank',
 'Poly Developments & Holdings Group',
 'Micron Technology',
 'ANZ',
 'Fubon Financial',
 'China Telecom',
 'HCA Healthcare',
 'Dow',
 'Telefónica',
 'China Vanke',
 'NAB - National Australia Bank',
 'Cathay Financial',
 'Qualcomm',
 "L'Oréal",
 'Allstate',
 'SAIC Motor',
 'ICICI Bank',
 'China Everbright Bank',
 'Gilead Sciences',
 'China Pacific Insurance',
 'NVIDIA',
 'Amgen',
 'Union Pacific',
 'Nike',
 'Takeda Pharmaceutical',
 'Dai-ichi Life Insurance',
 'Philip Morris International',
 'PayPal',
 'China Resources Land',
 'Midea Group',
 'Oversea-Chinese Banking',
 'Travelers',
 'Eli Lilly',
 'Mondelez International',
 "McDonald's",
 'General Electric',
 'Société Générale',
 'Schneider Electric',
 '3M',
 'Aflac',
 'Oil & Natural Gas',
 'Southern Company',
 'Deutsche Bank',
 'PTT',
 'CK Hutchison',
 'Canadian Natural Resources',
 'Sun Life Financial',
 'Northrop Grumman',
 'Archer Daniels Midland',
 'Marathon Petroleum',
 'China Minsheng Bank',
 'Legal & General Group',
 'Netflix',
 'Progressive',
 'Longfor Group Holdings',
 'Cosco Shipping',
 'DBS',
 'China Communications Construction',
 'NatWest Group',
 'Exelon',
 'Humana',
 'General Dynamics',
 'Power Corp of Canada',
 'Qatar National Bank',
 'Bayer',
 'KKR',
 'Country Garden Holdings',
 'NextEra Energy',
 'China Railway Group',
 'KB Financial Group',
 'HP',
 'Seven & I Holdings',
 'Nordea Bank',
 'Suncor Energy',
 'Salesforce.com',
 'Air Liquide',
 'Denso',
 'Bank of New York Mellon',
 'Mastercard',
 'Banco do Brasil',
 'Centene',
 'HDFC',
 'Freeport-McMoRan',
 'Merck KGaA, Darmstadt, Germany and its affiliates',
 'ABB',
 'Volvo Group',
 'CaixaBank',
 'Occidental Petroleum',
 'National Grid',
 'McKesson',
 'Shinhan Financial Group',
 'ASML Holding',
 'Nutrien',
 'Investor AB',
 'KIA',
 'Saint-Gobain',
 'Novo Nordisk',
 'Posco',
 'Diageo',
 'Royal Ahold Delhaize N.V.',
 'Dominion Energy',
 'Kroger',
 'Baoshan Iron & Steel',
 'Kweichow Moutai',
 'Xiaomi',
 'Bank of Ningbo',
 'Ecopetrol',
 'LyondellBasell Industries',
 'Contemporary Amperex Technology',
 'UniCredit',
 'AmerisourceBergen',
 'EssilorLuxottica',
 'Inditex',
 'Starbucks',
 'Nucor',
 'IntercontinentalExchange',
 'TJX Cos',
 'Tesco',
 'KBC Group',
 'BOE Technology Group',
 'Blackstone',
 'American Electric',
 'Macquarie Group',
 'Marubeni',
 'Swiss Re',
 'EOG Resources',
 'CNP Assurances',
 'Automatic Data Processing',
 'Phillips 66',
 'Tyson Foods',
 'Repsol',
 'Sumitomo',
 'Holcim',
 'Altria Group',
 'Applied Materials',
 'Daimler Truck Holding',
 'Zijin Mining Group',
 'The Saudi National Bank',
 'Richemont',
 'Kering',
 'Saudi Electricity',
 'Danone',
 'Nippon Steel',
 'LG Chem',
 'Discover Financial Services',
 'Couche Tard',
 'Huaxia Bank',
 'NN Group',
 'Fannie Mae',
 'Fresenius',
 'Marsh & McLennan',
 'Ameriprise Financial',
 'Becton Dickinson',
 'Panasonic',
 'MS&AD Insurance',
 'Orix',
 'Citic Securities',
 'First Abu Dhabi Bank',
 'BCE',
 'Schlumberger',
 'Texas Instruments',
 'Bank Rakyat Indonesia (BRI)',
 'CRH',
 'Standard Chartered',
 'Paramount',
 'Bank of Beijing',
 'Bank Of Jiangsu',
 'DuPont de Nemours',
 'Gree Electric Appliances',
 'Indian Oil',
 'Dollar General',
 'Kraft Heinz Company',
 'Wilmar International',
 'Freddie Mac',
 'Hewlett Packard Enterprise',
 'Japan Tobacco',
 'Poste Italiane',
 'United Overseas Bank',
 'China Unicom',
 'Valero Energy',
 'CSX',
 'Fortescue Metals Group',
 'Danske Bank',
 'China Railway Construction',
 'Moderna',
 'Woolworths',
 'Anhui Conch Cement',
 'Adobe',
 'Hartford Financial Services',
 'State Street',
 'Al Rajhi Bank',
 'Power Construction Corporation of China',
 'Shin-Etsu Chemical',
 'Fiserv',
 'Regeneron Pharmaceuticals',
 'ENEOS Holdings',
 'Tata Consultancy Services',
 'Sompo',
 'OMV Group',
 'Swiss Life Holding',
 'Bank Of Shanghai',
 'American Tower',
 'Pioneer Natural Resources',
 'Sun Hung Kai Properties',
 'Wanhua Chemical Group',
 'Sampo',
 'China Merchants Shekou Industrial Zone Holdings',
 'Haier Smart Home',
 'Eaton',
 'SK',
 'Johnson Controls International',
 'JBS',
 'Saudi Telecom',
 'Jardine Matheson',
 'Canadian National Railway',
 'Stryker',
 'Nokia',
 'Mitsubishi Electric',
 'Nissan Motor',
 'Tata Steel',
 'Heineken',
 'BAE Systems',
 'Etisalat',
 'BT Group',
 'Novatek',
 'CTBC Financial',
 'Greenland Holdings Group',
 'RWE Group',
 'Daikin Industries',
 'Aegon',
 'Baidu',
 'Ericsson',
 'Canon',
 'Lennar',
 'Bank of Nanjing',
 'Philips',
 'Keurig Dr Pepper',
 'China Yangtze Power',
 'DNB Bank',
 'Emerson Electric',
 'Imperial Brands',
 'Boeing',
 'General Mills',
 'Axis Bank',
 'National Bank of Canada',
 'The Estée Lauder Companies',
 'CNH Industrial',
 'Fairfax Financial',
 'Adidas',
 'Michelin Group',
 'Norfolk Southern',
 'Principal Financial Group',
 'Sempra',
 'Fortum',
 'Grupo Mexico',
 'D.R. Horton',
 'L3Harris Technologies',
 'Naspers',
 'Standard Bank Group',
 'TC Energy',
 'Norilsk Nickel',
 'Naturgy Energy Group',
 'Waste Management',
 'Henkel',
 'China State Construction Engineering',
 'MediaTek',
 'Recruit Holdings',
 'Hengli Petrochemical',
 'Xcel Energy',
 'Corteva',
 'Synchrony Financial',
 'Toyota Tsusho',
 'Toyota Industries',
 'AstraZeneca',
 'Sunac China Holdings',
 'China Evergrande Group',
 'Bridgestone',
 'Emirates NBD',
 'Daiwa House Industry',
 'JD.com',
 'Kinder Morgan',
 'China National Building',
 'Fifth Third Bank',
 'FirstRand',
 'Carrefour',
 'Fujitsu',
 'SEB AB',
 'Surgutneftegas',
 'New China Life Insurance',
 'Barrick Gold',
 'DSV Panalpina',
 'Talanx',
 'Vodafone',
 'Nintendo',
 'Hana Financial Group',
 'Hyundai Mobis',
 'NTPC',
 'Maybank',
 'CME Group',
 'TAQA',
 'Pernod Ricard',
 'Bank Mandiri',
 'Femsa',
 'Paccar',
 'Consolidated Edison',
 'Mitsui Fudosan',
 'Evergreen Marine Corp. (Taiwan)',
 'Komatsu',
 'Shaanxi Coal Industry',
 'Lenovo Group',
 'Fast Retailing',
 'London Stock Exchange',
 'Vonovia',
 'Aviva',
 'Sherwin-Williams',
 'Fujifilm Holdings',
 'Intuit',
 'Lam Research',
 'Erste Group Bank',
 'Lincoln National',
 'Carrier Global',
 'DISH Network',
 'China Coal Energy',
 'Continental',
 'VTB Bank',
 'Murata Manufacturing',
 'Larsen & Toubro',
 'Ally Financial',
 'NetEase',
 'Bank Central Asia',
 'Volvo Car',
 'Intact Financial',
 'Orsted',
 'Cummins',
 'Williams',
 'Capgemini',
 'Prologis',
 'Thales',
 'Bouygues',
 'Banorte',
 'CK Asset Holdings',
 'Orange',
 'Kuehne & Nagel International',
 'Bunge',
 'VMware',
 'Albertsons',
 'Samsung Life Insurance',
 'CRRC',
 'CBRE Group',
 'Toshiba',
 'Samsung C&T',
 'Infosys',
 'Prudential',
 'Yankuang Energy Group',
 'Canadian Pacific Railway',
 'Loews',
 'Tokyo Electron',
 'LG Electronics',
 'CSL',
 'Magna International',
 'Analog Devices',
 'Kubota',
 'Newmont Mining',
 'TE Connectivity',
 'Air Products & Chemicals',
 'Aon',
 'TELUS',
 'Dollar Tree',
 'KeyCorp',
 'Willis Towers Watson',
 'Wesfarmers',
 'China Zheshang Bank',
 'Suzuki Motor',
 'Best Buy',
 'SVB Financial Group',
 'Advanced Micro Devices',
 'Markel',
 'Muyuan Foodstuff',
 'Kimberly-Clark',
 'Cognizant',
 'Swedbank',
 'Corning',
 'Infineon Technologies',
 'Citizens Financial Group',
 'Devon Energy',
 'Asahi Group Holdings',
 'JSW Steel',
 'Lumen Technologies',
 'Regions Financial',
 'Svenska Handelsbanken',
 'Raymond James Financial',
 'BYD',
 'Illinois Tool Works',
 'Pinduoduo',
 'Activision Blizzard',
 'Liberty Global',
 'Colgate-Palmolive',
 'SSE',
 'Nan Ya Plastics',
 'Vivendi',
 'Baxter International',
 'Fosun International',
 'Weichai Power',
 'Fidelity National Financial',
 'Parker-Hannifin',
 'Vedanta Limited',
 'Woori Financial Group',
 'Sysco',
 'Telstra',
 'Rogers Communications',
 'Credit Suisse Group',
 'M&T Bank',
 'Boston Scientific',
 'Edison International',
 "Financiere de l'Odet",
 'Entergy',
 'Swisscom',
 'EnBW-Energie Baden',
 'Sumitomo Mitsui Trust',
 'Hikvision',
 'Nippon Yusen',
 'Stanley Black & Decker',
 'Oneok',
 'Marriott International',
 'Warner Bros. Discovery',
 'S.F. Holding',
 'Delta Air Lines',
 'Bharat Petroleum',
 'Halliburton',
 'Metallurgical Corp of China',
 'Northern Trust',
 'HeidelbergCement',
 'China Steel',
 'Eversource Energy',
 'Sany Heavy Industry',
 'Hermès International',
 'International Paper',
 'Koç Holding',
 'Nidec',
 'Meituan',
 'Kotak Mahindra Bank',
 'Teck Resources',
 'Southwest Airlines',
 'Deutsche Boerse',
 'LabCorp',
 'China Tower Corp.',
 'Inpex',
 'Coca-Cola European Partners',
 'Wuliangye Yibin',
 'Shimao Property Holdings',
 'Idemitsu Kosan',
 'Formosa Petrochemical',
 'Crown Castle International',
 'FirstEnergy',
 'Rongsheng Petrochemical',
 'Hindalco Industries',
 'Renault',
 'Bank Of Hangzhou',
 'International Holding Company',
 'Cincinnati Financial',
 'Mitsubishi Estate',
 'Cleveland-Cliffs',
 'Grupo ACS',
 'CGN Power',
 'ASE Technology Holding',
 'JFE Holdings',
 'DTE Energy',
 'China Hongqiao Group',
 'NXP Semiconductors',
 'Western Digital',
 'Booking Holdings',
 'Aeon',
 'First Republic Bank',
 'Lufax Holding',
 'Atlas Copco',
 'Fidelity National Information (FIS)',
 'Mitsubishi Chemical',
 'Edp-energias De Portugal',
 'Kyocera',
 'Xiamen C&D',
 'AutoZone',
 'China Taiping Insurance',
 'PICC',
 'Cenovus Energy',
 'Neste',
 'Porsche Automobil Holding',
 'H&M - Hennes & Mauritz',
 'RELX',
 'PG&E',
 'Republic Services',
 'Ross Stores',
 'WEC Energy Group',
 'Cardinal Health',
 'CarMax',
 'China Development Financial',
 'Riyad Bank',
 'Thomson Reuters',
 'Transneft',
 'Ferguson',
 'IQVIA',
 'Hong Kong Exchanges',
 'PPG',
 'Legend Holding',
 'Ecolab',
 'Sinopharm Group',
 'Luxshare Precision Industry',
 'Seazen Group',
 'Global Payments',
 'China Energy Engineering',
 'Safran',
 'S&P Global',
 'Huntington Bank',
 'Arch Capital Group',
 'Jackson Financial',
 'Bank Leumi',
 'Trane Technologies',
 'Veolia Environnement',
 "O'Reilly Automotive",
 'Biogen',
 'Publicis Groupe',
 'Hanwha',
 'Mosaic',
 'Bharti Airtel',
 'Daqin Railway',
 'Uber',
 'STMicroelectronics',
 'Gemdale',
 'Ageas',
 'Quanta Computer',
 'George Weston',
 'Weyerhaeuser',
 'Korea Electric Power',
 'Fox',
 'Mitsubishi Heavy Industries',
 'Steel Dynamics',
 'Keyence',
 'Longi Green Energy Technology',
 'Reckitt Benckiser Group',
 'Coal India',
 'Aisin Seiki',
 'Digital Realty Trust',
 'Tata Motors',
 'Simon Property Group',
 'Resona Holdings',
 'Industrial Bank of Korea',
 'CLP Holdings',
 'National Bank of Kuwait',
 'SingTel',
 'Coinbase',
 'CenterPoint Energy',
 'Saudi Arabian Mining',
 'China Cinda Asset Management',
 'Asahi Kasei',
 'NEC',
 'United Airlines Holdings',
 'MGM Resorts',
 'DSM',
 'Telkom Indonesia',
 'PKN Orlen',
 'Guotai Junan Securities',
 'Norsk Hydro',
 'Formosa Plastics',
 'NRG Energy',
 'Public Bank',
 'TCL',
 'Huatai Securities',
 'Kellogg',
 'Inner Mongolia Yili',
 'WPP',
 'Omnicom Group',
 'Sekisui House',
 'Cheniere Energy',
 'Sandvik',
 'Siam Cement',
 'East Japan Railway',
 'Abu Dhabi Commercial Bank',
 'Huishang Bank',
 'Great Wall Motor',
 'Haitong Securities',
 'Dongfeng Motor Group',
 'China Reinsurance Group',
 'Henderson Land',
 'Samsung SDI',
 'Fortis (Canada)',
 'SK Telecom',
 'HAL Trust',
 'Banco Btg Pactual',
 'Gallagher',
 'Baker Hughes Company',
 'Everest Re Group',
 'Amphenol',
 'American Airlines Group',
 'Astellas Pharma',
 'KLA',
 'Otsuka Holding',
 'China Bohai Bank',
 'Kasikornbank',
 'Bank Hapoalim',
 'Woodside Petroleum',
 'MTR',
 'Tatneft',
 'Power Finance',
 'Zoetis',
 'Lonza Group',
 'Eiffage',
 'Sumitomo Chemical',
 'Vertex Pharmaceuticals',
 'Constellation Energy',
 'CIFI Holdings Group',
 'Raiffeisen Bank International',
 'Whirlpool',
 'Siemens Energy',
 'WestRock',
 'Samsung Fire & Marine',
 'US Steel',
 'UPM-Kymmene',
 'Formosa Chemicals',
 'SK Innovation',
 'Telia',
 'T&D Holdings',
 'Mapfre',
 'HCL Technologies',
 'Sumitomo Realty',
 'Westlake Chemical',
 'Apollo Global Management',
 'United Rentals',
 'Diamondback Energy',
 'Chongqing Rural Bank',
 'Otis Worldwide',
 'Ball',
 'Stora Enso',
 'Yang Ming Marine Transport',
 'Wipro',
 'Phoenix Group Holdings',
 'Power Grid of India',
 'Absa Group',
 'Sumitomo Electric',
 'Novolipetsk Steel',
 "St. James's Place",
 'Grasim Industries',
 'Segro',
 'Mega Financial Holding',
 'Zhongsheng Group Holdings',
 'Shin Kong Financial',
 'CMS Energy',
 'Quinenco',
 'Evonik Industries',
 'East Money Information',
 'QBE Insurance Group',
 'Tenaga Nasional',
 'Naver',
 'TDK',
 'Nomura',
 'Jinke Property Group',
 'Tokyo Electric Power',
 'CDW',
 'The Hershey Company',
 'Pgnig Group',
 'ITC',
 'MTN Group',
 'Compass Group',
 'WR Berkley',
 "Moody's",
 'Genuine Parts',
 'Beijing-Shanghai High-Speed Railway',
 'Aluminum Corp of China',
 'Kansai Electric Power',
 'Public Storage',
 'China International Travel Service',
 'Sika',
 'Signature Bank',
 'International Flavors & Fragrances',
 'T Rowe Price',
 'Atlantia',
 'Roper Technologies',
 'Shanghai International Port',
 'Daiichi Sankyo',
 'Rakuten',
 'Franklin Resources',
 'Bank of Ireland',
 'Mitsui OSK Lines',
 'Saudi British Bank',
 'Ameren',
 'Chunghwa Telecom',
 'Assa Abloy',
 'ZTE',
 'Asr Nederland',
 'Conagra Brands',
 'Bajaj Finserv',
 'Commerzbank',
 'Hyundai Steel',
 'LG Display',
 'Logan Property Holdings',
 'Public Service Enterprise Group',
 'KT',
 'EN+ Group International',
 'Isbank',
 'Expeditors International',
 'Ternium',
 'CEZ Group',
 'Isuzu Motors',
 'Renesas Electronics',
 'Universal Music Group',
 'Unipol Gruppo',
 'SBI Holdings',
 'Techtronic Industries',
 'Ferrovial',
 'CIMB Group Holdings',
 'E-mart',
 'Kone',
 'GF Securities',
 'China Merchants Securities',
 'Annaly Capital Management',
 'Coles Group',
 'Central Japan Railway',
 'Sabanci Holding',
 'Yuanta Financial Holding',
 'AntarChile',
 'HMM',
 'Alleghany',
 'Guosen Securities',
 'Seagate Technology',
 'Avis Budget Group',
 'Jiangxi Copper',
 'Mitsubishi UFJ Lease',
 'Sumitomo Metal Mining',
 'Asustek Computer',
 'Associated British Foods',
 'China National Nuclear Power',
 'China International Capital',
 'China Molybdenum',
 'Covestro',
 'Equitable Holdings',
 'M&G',
 'Shopify',
 'Shanghai Construction',
 'Essity',
 'Canara Bank',
 'WW Grainger',
 'Viatris',
 'American Water Works',
 'United Microelectronics',
 'VF',
 'Intuitive Surgical',
 'Snam',
 'Vestas Wind Systems',
 'Subaru',
 'Jiangsu Zhongnan Construction Group',
 'Carlsberg',
 'Semiconductor Manufacturing International',
 'PKO Bank Polski',
 'Builders FirstSource',
 'ENN Energy Holdings',
 'WH Group',
 'Amcor',
 'Korea Gas',
 'Jefferies Financial',
 'Alexandria Real Estate Equities',
 'Julius Baer Group',
 'Sanlam',
 'Severstal',
 'Emaar Properties',
 'Joint Stock Commercial Bank for Foreign Trade of Vietnam',
 'Shanghai Rural Commercial Bank',
 'Motorola Solutions',
 'Braskem',
 'Bank of Baroda',
 'S-Oil',
 'Suncorp Group',
 'Tractor Supply',
 'MOL Hungarian Oil',
 'Aptiv',
 'Voya Financial',
 'GS Holdings',
 'Gerdau (Cosigua)',
 'Equity Residential',
 'Qatar Islamic Bank',
 'Hormel Foods',
 'Shenwan Hongyuan Group',
 'Reinsurance Group of America',
 'Quest Diagnostics',
 'Solvay',
 'Pembina Pipeline',
 'Banque Saudi Fransi',
 'SMC',
 'Sasol',
 'Molson Coors Brewing',
 "Macy's",
 'Bancolombia',
 'China International Marine',
 'Cintas',
 'Huaneng Power International',
 'Restaurant Brands International',
 'Grupa PZU',
 'Kao',
 'Agile Group Holdings',
 'Arrow Electronics',
 'Tenet Healthcare',
 'Shenzhen Overseas',
 'Grupo Aval',
 'CP All',
 'Geely Automobile Holdings',
 'Centrica',
 'Dubai Islamic Bank',
 'Suzano Papel e Celulose',
 'Link REIT',
 'Yum! Brands',
 'First Quantum Minerals',
 'AerCap Holdings',
 'First Horizon',
 'Dentsu',
 'Molina Healthcare',
 'Union Bank of India',
 ...]

In [109]:
# Quantidade de dados
dados.shape

(2000, 7)

In [110]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rank            2000 non-null   int64
 1   global company  2000 non-null   object
 2   country         2000 non-null   object
 3   sales           2000 non-null   object
 4   profit          2000 non-null   object
 5   assets          2000 non-null   object
 6   market value    2000 non-null   object
dtypes: int64(1), object(6)
memory usage: 109.5+ KB

In [111]:
# Países com mais empresas:
paises = dados.country.value_counts()
paises

United States           590
China                   297
Japan                   196
South Korea              65
United Kingdom           64
Canada                   58
India                    55
France                   54
Hong Kong                54
Germany                  52
Taiwan                   48
Switzerland              40
Sweden                   32
Australia                30
Italy                    26
Netherlands              24
Russia                   24
Brazil                   23
Ireland                  21
Spain                    21
Saudi Arabia             16
Thailand                 14
Israel                   13
South Africa             13
United Arab Emirates     13
Denmark                  11
Singapore                11
Turkey                    9
Austria                   9
Finland                   9
Luxembourg                9
Mexico                    9
Poland                    8
Norway                    8
Indonesia                 7
Malaysia                  7
Belgium                   7
Chile                     6
Qatar                     5
Greece                    5
Philippines               5
Vietnam                   5
Portugal                  4
Colombia                  3
Kuwait                    3
Bermuda                   3
Hungary                   2
Morocco                   2
Kazakhstan                2
Cayman Islands            1
Egypt                     1
Argentina                 1
Czech Republic            1
Bahrain                   1
Uruguay                   1
Peru                      1
Nigeria                   1
Name: country, dtype: int64

In [112]:
# Selecione qualquer pais:
paises.Brazil

23

## Principais Empresas na America Latina:

In [113]:
america_do_sul = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 
                  'French Guiana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela']
empresas_sulamericanas = dados.query('country in @america_do_sul')

In [114]:
empresas_sulamericanas.index = range(empresas_sulamericanas.shape[0])
empresas_sulamericanas

,rank,global company,country,sales,profit,assets,market value
0,65,Petrobras,Brazil,$83.89 B,$19.77 B,$174.68 B,$83.98 B
1,117,Vale,Brazil,$54.4 B,$22.47 B,$89.61 B,$82.03 B
2,137,Itaú Unibanco Holding,Brazil,$35.96 B,$4.96 B,$372.3 B,$52.89 B
3,181,Banco Bradesco,Brazil,$28.33 B,$4.07 B,$296.89 B,$43.16 B
4,267,Banco do Brasil,Brazil,$29.54 B,$3.4 B,$362.53 B,$20.7 B
5,294,Ecopetrol,Colombia,$23.43 B,$4.45 B,$60.01 B,$36.07 B
6,399,JBS,Brazil,$64.99 B,$3.8 B,$37.18 B,$17.48 B
7,774,Banco Btg Pactual,Brazil,$2.71 B,$848.1 M,$68.31 B,$56.14 B
8,833,Quinenco,Chile,$8.46 B,$2.49 B,$72.47 B,$4.84 B
9,905,AntarChile,Chile,$24.9 B,$1.21 B,$25.87 B,$3.49 B
10,953,Braskem,Brazil,$19.57 B,$2.59 B,$16.62 B,$6.76 B
11,962,Gerdau (Cosigua),Brazil,$14.52 B,$2.87 B,$13.25 B,$10.16 B
12,976,Bancolombia,Colombia,$6.08 B,$1.09 B,$71.22 B,$10.89 B
13,987,Grupo Aval,Colombia,$10.27 B,$879.7 M,$90.15 B,$4.78 B
14,992,Suzano Papel e Celulose,Brazil,$7.59 B,$1.6 B,$21.36 B,$14.66 B
15,1002,Eletrobrás,Brazil,$6.97 B,$1.05 B,$33.42 B,$13.42 B
16,1111,Credicorp,Peru,$4.89 B,$915.7 M,$61.35 B,$11.7 B
17,1141,Itaúsa,Brazil,$1.51 B,$2.26 B,$15.44 B,$18.42 B
18,1165,Falabella,Chile,$15.1 B,$857 M,$25.16 B,$7.27 B
19,1257,Raizen,Brazil,$30.14 B,$619 M,$18.86 B,$1.36 B
20,1324,CSN,Brazil,$8.88 B,$2.27 B,$14.25 B,$6.22 B
21,1401,MercadoLibre,Uruguay,$7.07 B,$83.3 M,$10.1 B,$49.4 B
22,1456,XP,Brazil,$2.31 B,$665.9 M,$25.02 B,$14.29 B
23,1470,Metalurgica Gerdau,Brazil,$14.52 B,$904.1 M,$13.39 B,$2.6 B
24,1482,BCI-Banco Credito,Chile,$3.55 B,$649.4 M,$79.32 B,$5.07 B
25,1495,Marfrig Global Foods,Brazil,$15.82 B,$804.6 M,$8.62 B,$2.62 B
26,1539,B3,Brazil,$1.71 B,$874.2 M,$9.63 B,$18.37 B
27,1545,WEG,Brazil,$4.37 B,$664.5 M,$4.3 B,$27.68 B
28,1606,YPF,Argentina,$13.02 B,$2.7 M,$23.27 B,$3.31 B
29,1652,Usiminas,Brazil,$6.47 B,$1.75 B,$8.23 B,$3.1 B
30,1726,SQM,Chile,$2.91 B,$606.4 M,$7.26 B,$22.11 B
31,1807,Ultrapar Participacoes,Brazil,$20.34 B,$157.6 M,$6.99 B,$3.26 B
32,1853,CPFL Energia,Brazil,$7.27 B,$879.9 M,$11.87 B,$8.47 B
33,1916,Cencosud,Chile,$14.43 B,$434.8 M,$15.21 B,$4.96 B
34,1943,Bradespar,Brazil,$0 M,$1.5 B,$1.36 B,$2.43 B

#### Na América do Sul, o Brasil possui a maior quantidade das maiores empresas do mundo.

### Empresas do Brasil:

In [120]:
brasil = ['Brazil']
empresas_brasil = empresas_sulamericanas.query('country in @brasil')
empresas_brasil.index = range(empresas_brasil.shape[0])
empresas_brasil

,rank,global company,country,sales,profit,assets,market value
0,65,Petrobras,Brazil,$83.89 B,$19.77 B,$174.68 B,$83.98 B
1,117,Vale,Brazil,$54.4 B,$22.47 B,$89.61 B,$82.03 B
2,137,Itaú Unibanco Holding,Brazil,$35.96 B,$4.96 B,$372.3 B,$52.89 B
3,181,Banco Bradesco,Brazil,$28.33 B,$4.07 B,$296.89 B,$43.16 B
4,267,Banco do Brasil,Brazil,$29.54 B,$3.4 B,$362.53 B,$20.7 B
5,399,JBS,Brazil,$64.99 B,$3.8 B,$37.18 B,$17.48 B
6,774,Banco Btg Pactual,Brazil,$2.71 B,$848.1 M,$68.31 B,$56.14 B
7,953,Braskem,Brazil,$19.57 B,$2.59 B,$16.62 B,$6.76 B
8,962,Gerdau (Cosigua),Brazil,$14.52 B,$2.87 B,$13.25 B,$10.16 B
9,992,Suzano Papel e Celulose,Brazil,$7.59 B,$1.6 B,$21.36 B,$14.66 B
10,1002,Eletrobrás,Brazil,$6.97 B,$1.05 B,$33.42 B,$13.42 B
11,1141,Itaúsa,Brazil,$1.51 B,$2.26 B,$15.44 B,$18.42 B
12,1257,Raizen,Brazil,$30.14 B,$619 M,$18.86 B,$1.36 B
13,1324,CSN,Brazil,$8.88 B,$2.27 B,$14.25 B,$6.22 B
14,1456,XP,Brazil,$2.31 B,$665.9 M,$25.02 B,$14.29 B
15,1470,Metalurgica Gerdau,Brazil,$14.52 B,$904.1 M,$13.39 B,$2.6 B
16,1495,Marfrig Global Foods,Brazil,$15.82 B,$804.6 M,$8.62 B,$2.62 B
17,1539,B3,Brazil,$1.71 B,$874.2 M,$9.63 B,$18.37 B
18,1545,WEG,Brazil,$4.37 B,$664.5 M,$4.3 B,$27.68 B
19,1652,Usiminas,Brazil,$6.47 B,$1.75 B,$8.23 B,$3.1 B
20,1807,Ultrapar Participacoes,Brazil,$20.34 B,$157.6 M,$6.99 B,$3.26 B
21,1853,CPFL Energia,Brazil,$7.27 B,$879.9 M,$11.87 B,$8.47 B
22,1943,Bradespar,Brazil,$0 M,$1.5 B,$1.36 B,$2.43 B

## Principais Empresas na Europa:

In [222]:
paises_europa = ['Albania', 'Germany', 'Andorra', 'Armenia', 'Austria', 'Azerbaijan', 'Belgium',
                 'Belarus', 'Bosnia', 'Herzegovina', 'Bulgaria', 'Kazakhstan', 'Cyprus',
                 'Croatia', 'Denmark', 'Slovakia', 'Slovenia', 'Spain', 'Estonia', 'Finland',
                 'France', 'Georgia', 'Greece', 'Hungary', 'Ireland', 'Iceland', 'Italy', 'Latvia',
                 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia', 'Malta', 'Moldova', 'Monaco',
                 'Montenegro', 'Norway', 'Netherlands', 'Poland', 'Portugal', 'United Kingdom',
                 'Czech Republic', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Sweden', 'Switzerland',
                 'Turkey', 'Ukraine', 'Vatican']
empresas_europa = dados.query('country in @paises_europa')

In [225]:
empresas_europa.index = range(empresas_europa.shape[0])
empresas_europa.country.value_counts()

United Kingdom    64
France            54
Germany           52
Switzerland       40
Sweden            32
Italy             26
Russia            24
Netherlands       24
Ireland           21
Spain             21
Denmark           11
Luxembourg         9
Finland            9
Austria            9
Turkey             9
Norway             8
Poland             8
Belgium            7
Greece             5
Portugal           4
Hungary            2
Kazakhstan         2
Czech Republic     1
Name: country, dtype: int64

### Na Europa, a Inglaterra possui a maior quantidade das maiores empresas do mundo

## Principais Empresas na Ásia:

In [226]:
paises_asia = ['Afghanistan','Saudi Arabia', 'Armenia', 'Azerbaijan','Bahrain',
               'Bangladesh', 'Brunei', 'Bhutan', 'Cambodia', 'Kazakhstan', 'Qatar',
               'China', 'Cyprus', 'Singapore', 'North Korea', 'South Korea', 'Egypt',
               'Arab emirates', 'Philippines', 'Georgia', 'Yemen', 'India', 'Indonesia',
               'Will', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kuwait', 'Laos', 'Lebanon',
               'Malaysia', 'Maldives', 'Myanmar', 'Mongolia', 'Nepal', 'Oman', 'Pakistan',
               'kyrgyzstan', 'Russia', 'Syria', 'Sri Lanka', 'tajikistan', 'thailand',
               'East Timor', 'Turkmenistan', 'Turkey', 'uzbekistan', 'Vietnam']
empresas_asia = dados.query('country in @paises_asia')

In [228]:
empresas_asia.index = range(empresas_asia.shape[0])
empresas_asia.country.value_counts()

China           297
Japan           196
South Korea      65
India            55
Russia           24
Saudi Arabia     16
Israel           13
Singapore        11
Turkey            9
Malaysia          7
Indonesia         7
Qatar             5
Vietnam           5
Philippines       5
Kuwait            3
Kazakhstan        2
Bahrain           1
Egypt             1
Name: country, dtype: int64

### Na Ásia, a China lidera o rank possuindo as maiores empresas do mundo

## Principais Empresas na Oceania:

In [229]:
paises_oceania = ['Australia', 'Federated States of Micronesia', 'Fiji', 'Marshall Islands',
                  'Solomon Islands', 'Kiribati', 'Nauru', 'New Zealand', 'Palau', 'Papua New Guinea',
                  'Samoa', 'Tonga', 'Tuvalu', 'Vanuatu']
empresas_oceania = dados.query('country in @paises_oceania')

In [230]:
empresas_oceania.index = range(empresas_oceania.shape[0])
empresas_oceania

,rank,global company,country,sales,profit,assets,market value
0,75,BHP Group,Australia,$65.55 B,$16.92 B,$105.72 B,$178.07 B
1,106,Commonwealth Bank,Australia,$21.85 B,$8.39 B,$835.97 B,$130.34 B
2,173,Westpac Banking Group,Australia,$20.46 B,$4.1 B,$677.03 B,$61.42 B
3,191,ANZ,Australia,$18.38 B,$4.63 B,$707.08 B,$56.23 B
4,198,NAB - National Australia Bank,Australia,$15.76 B,$4.78 B,$669.03 B,$77.24 B
5,310,Macquarie Group,Australia,$11.21 B,$2.96 B,$251.79 B,$55.44 B
6,369,Fortescue Metals Group,Australia,$20.93 B,$8.89 B,$25.18 B,$47.37 B
7,372,Woolworths,Australia,$38.84 B,$6.01 B,$23.86 B,$34.61 B
8,546,CSL,Australia,$10.59 B,$2.36 B,$23.44 B,$94.67 B
9,558,Wesfarmers,Australia,$25.35 B,$1.65 B,$18.34 B,$40.57 B
10,596,Telstra,Australia,$15.82 B,$1.09 B,$31.16 B,$34.21 B
11,786,Woodside Petroleum,Australia,$7.01 B,$2.02 B,$26.47 B,$22.85 B
12,836,QBE Insurance Group,Australia,$13.95 B,$746.1 M,$43.37 B,$13.04 B
13,901,Coles Group,Australia,$29.38 B,$746.1 M,$15.2 B,$18.25 B
14,956,Suncorp Group,Australia,$9.88 B,$698.8 M,$72.31 B,$10.27 B
15,1021,Goodman Group,Australia,$1.27 B,$2.46 B,$13.93 B,$32.02 B
16,1231,Santos,Australia,$4.82 B,$656.3 M,$31.12 B,$19.97 B
17,1236,Bluescope Steel,Australia,$12.37 B,$1.88 B,$10.76 B,$7.74 B
18,1308,Transurban Group,Australia,$2.08 B,$-80.3 M,$28.09 B,$31.17 B
19,1356,South32,Australia,$6.58 B,$972.3 M,$13.98 B,$16.27 B
20,1372,Sonic Healthcare,Australia,$7.08 B,$1.1 B,$9.06 B,$12.68 B
21,1488,Newcrest Mining,Australia,$4.1 B,$900.2 M,$14.45 B,$18.29 B
22,1552,Scentre Group,Australia,$1.71 B,$666.4 M,$26.67 B,$11.02 B
23,1557,Atlassian,Australia,$2.43 B,$-530.8 M,$2.76 B,$62.18 B
24,1715,Ramsay Health Care,Australia,$9.75 B,$286.6 M,$12.47 B,$13.94 B
25,1791,Bank of Queensland,Australia,$1.58 B,$316 M,$68.86 B,$3.7 B
26,1811,Bendigo & Adelaide Bank,Australia,$1.52 B,$451.4 M,$66 B,$4.35 B
27,1924,Dexus,Australia,$680 M,$1.12 B,$14.09 B,$8.51 B
28,1946,Aristocrat Leisure,Australia,$3.56 B,$616 M,$6.26 B,$15.82 B
29,1977,Ampol,Australia,$16.08 B,$420.3 M,$6.44 B,$5.68 B

In [231]:
empresas_oceania.country.value_counts()

Australia    30
Name: country, dtype: int64

### Na Oceania, a Australia é a unica a possuir empresas listadas no rank das maiores do mundo